title: Andrei's Playground
email: notyet
github_username: psandrey
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

svg:
  optimize: true
# Build settings
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/

collections: 
  graph:
    output: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/