title: Andrei's Playground
email: notyet
github_username: psandrey
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

svg:
  optimize: true
# Build settings
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/

collections:

  analysis:
    output: true
    permalink: /analysis:name

  data_structures:
    output: true
    permalink: /data_structures:name

  paradigm:
    output: true
    permalink: /paradigm:name

  sort:
    output: true
    permalink: /sort/:name

  search:
    output: true
    permalink: /search:name

  graph:
    output: true
    permalink: /graph:name

  string:
    output: true
    permalink: /string:name

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/